//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBLibraryApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dolaplar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dolaplar()
        {
            this.Raflars = new HashSet<Raflar>();
        }
    
        public int Id { get; set; }
        public string DolapNo { get; set; }
        public int OdaId { get; set; }
    
        public virtual Odalar Odalar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Raflar> Raflars { get; set; }
        public object Dolaplars { get; internal set; }
    }
}
