//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBLibraryApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Raflar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Raflar()
        {
            this.Kitaplars = new HashSet<Kitaplar>();
        }
    
        public int Id { get; set; }
        public Nullable<int> RafNo { get; set; }
        public int DolapId { get; set; }
        public Nullable<bool> isStock { get; set; }
    
        public virtual Dolaplar Dolaplar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kitaplar> Kitaplars { get; set; }
    }
}
